Junctions:
    Plot_Speed: 
        type:   selectInput
        choices:
            - fast
            - accurate
        selected: fast        
    Locus_Padding: 
        type:   numericInput
        value:  50000
        min:    0
        max:    500000
        step:   50000
