Points:
    Size_By:
        type:   selectInput
        choices:
            - fixed
            - nSamples
            - nInstances
            - nSampleInstances
        value: none
    Color_By: 
        type:   selectInput
        choices:
            - edgeType
            - isSingleton
            - isSingleSample
            - sample
        value: edgeType
    Point_Size:
        type:   numericInput
        value:  0.25
        min:    0.1
        max:    2
        step:   0.05   
    Point_Scale_Factor:
        type:   numericInput
        value:  0.25
        min:    0.05
        max:    1
        step:   0.05 
