include:
    - height # Track options
settings:
    Amplicons:
        Plot_Spans_As:
            type: selectInput
            choices:
                - packed_spans 
                - unpacked_spans 
            value: packed_spans
        Pack_Padding_Fraction:
            type: numericInput
            value:  0.025
            min:    0.01 
            max:    0.10
            step:   0.005
        Span_Line_Width:
            type: numericInput
            value:  2
            min:    1
            max:    20
            step:   1
        Spans_Color_Palette:
            type: selectInput
            choices:
                - plotly
            value: plotly 
