Arcs:
    Line_Width:
        type:   numericInput
        value:  1
        min:    0.25
        max:    5
        step:   0.25 
    # Line_Scale_Factor:
    #     type:   numericInput
    #     value:  0.2
    #     min:    0.05
    #     max:    1
    #     step:   0.05 
    Color_By: 
        type:   selectInput
        choices:
            - edgeType
            - isSingleton
            - isSingleSample
            - sample
        value: edgeType 
    Upside_Down:
        type: checkboxInput
        value: false
