Arcs:
    Line_Width:
        type:   numericInput
        value:  1
        min:    0.25
        max:    5
        step:   0.25 
    # Line_Scale_Factor:
    #     type:   numericInput
    #     value:  0.2
    #     min:    0.05
    #     max:    1
    #     step:   0.05 
    Color_By: 
        type:   selectInput
        choices:
            - edgeType
            - isSingleton
            - isSingleSample
            - sample
        value: edgeType 
    Max_Y_BP: 
        type:   selectInput
        choices:
            - window_width
            - max_sv_width
            - fixed
        value: window_width 
    Fixed_Y_BP:
        type:   numericInput
        value:  500
        min:    10
        max:    10000
        step:   50
    Upside_Down:
        type: checkboxInput
        value: false
