Filters:
    Min_SV_Size:
        type:   numericInput
        value:  1
        min:    0
        max:    250000000
        step:   10000
    Max_SV_Size:
        type:   numericInput
        value:  0 # i.e., no limit
        min:    0
        max:    250000000
        step:   10000
    Min_Insert_Size:
        type:   numericInput
        value:  -50
        min:    -1000
        max:    1000
        step:   10
    Max_Insert_Size:
        type:   numericInput
        value:  50
        min:    -1000
        max:    1000
        step:   10 
    Min_Source_Molecules:
        type:   numericInput
        value:  1
        min:    1
        max:    10000
        step:   1    
    Max_Source_Molecules:
        type:   numericInput
        value:  0 # i.e., no limit
        min:    1
        max:    10000
        step:   1   
    Min_Sequenced_Molecules:
        type:   numericInput
        value:  0
        min:    0
        max:    10
        step:   1
    Max_Linked_Junctions:
        type:   numericInput
        value:  0
        min:    0
        max:    100
        step:   1         
    Min_Samples_With_SV:
        type:   numericInput
        value:  1
        min:    1
        max:    100
        step:   1   
    Max_Samples_With_SV:
        type:   numericInput
        value:  0 # i.e., no limit
        min:    1
        max:    100
        step:   1  
    Unique_To_Sample:
        type:   selectInput
        choices:
            - show all SVs
        value: show all SVs
    Show_ChrM:
        type:   selectInput
        choices:
            - always
            - translocations_only
            - never
        value: never  
    Min_Map_Quality:
        type:   numericInput
        value:  0
        min:    0
        max:    60
        step:   5  
    Min_Flank_Length:
        type:   numericInput
        value:  0
        min:    0
        max:    1000
        step:   50  
    # SPACER_1:
    #     type: spacer 
    SV_Type:
        type:   checkboxGroupInput
        choices:
            - Del
            - Dup
            - Inv
            - Trans
        value:
            - Del
            - Dup
            - Inv
        inline: TRUE
