Points:
    Size_By:
        type:   selectInput
        choices:
            - fixed
            - nSamples
            - nInstances
        value: nInstances
    Color_By: 
        type:   selectInput
        choices:
            - edgeType
            - isSingleton
            - isSingleSample
            - sample
        value: edgeType
    Point_Size:
        type:   numericInput
        value:  0.5
        min:    0.25
        max:    2
        step:   0.25   
    Point_Scale_Factor:
        type:   numericInput
        value:  0.2
        min:    0.05
        max:    1
        step:   0.05 
