include:
    - height
trackType:
    - svx_amplicons
# shared:
#     - svArc_settings.yml
#     - svAmpliconFilter_settings.yml # shared with other amplicon apps, e.g., svDJ
#     - ../svAmplicon_filters.yml # specific to this app
# #     - svJunction_settings.yml
# #     - ../junction_settings.yml    
# #     - svSummarize_settings.yml
