include:
    - height
shared:
    - svPoint_settings.yml
    - svFilter_settings.yml
    - svJunction_settings.yml
    - ../junction_settings.yml    
    - svSummarize_settings.yml
# presets:
#     Test:
#         Points:
#             Point_Scale_Factor: 0.1
