settings:
    Coverage:
        Plot_Type:
            type:   selectInput
            choices:
                - Read Depth
                - Copy Number
            value:  Copy Number
        Median_Ploidy:
            type:   numericInput
            value:  2
            min:    1
            max:    10
            step:   1
