#----------------------------------------------------------------------
# R package dependencies common to many apps
#----------------------------------------------------------------------
packages:
  R:  
    - data.table
    - imager
    - abind
    - twosamples
  Bioconductor: null
