---
pipeline:
    name: svAmplicon
    description: "Analyze targeted amplicon sequences for evidence of deletions and other SVs"
    version: v0.0.0
suiteVersions:
    genomex-mdi-tools: main 
actions:
    _global:  
        environment: svAmplicon  
        condaFamilies:
            - genomex-mdi-tools//base
            - genomex-mdi-tools//genome
            - r-4.2
        optionFamilies:
            - genomex-mdi-tools//genome
    align:
        order: 1
        module: genomex-mdi-tools//align/dna-paired-end 
    collate:
        order: 2
        condaFamilies:
            - genomex-mdi-tools//bwa
        optionFamilies: # these options apply to all actions
            - genomex-mdi-tools//bam-format
            - genomex-mdi-tools//read-filtering
            - genomex-mdi-tools//read-merging
            - amplicon-discovery
            - read-pair-filtering
            - sv-finding
        resources:
            required:
                total-ram: 32G
            recommended: 
                n-cpu: 16
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 12:00:00
        description: "group molecules by sequence identity, discover and characterize amplicon(s)"
optionFamilies:   
    amplicon-discovery:
        options:
            match-keep-distance:
                order: 1
                short: k
                type: integer
                required: false
                default: 5
                description: "keep molecules with outer endpoints <=k bp from an amplicon index position"  
            match-reject-distance:
                order: 2
                short: K
                type: integer
                required: false
                default: 50
                description: "reject molecules with outer endpoints >k and <=K bp from an amplicon index position" 
            max-amplicons:
                order: 3
                short: A
                type: integer
                required: false
                default: 1
                description: "allow at most -A amplicons to be discovered, in order of abundance"
            min-fraction-add-index:
                order: 4
                short: a
                type: double
                required: false
                default: 0.05
                description: "additional amplicons must exceed this fraction coverage of the first amplicon"
            max-insert-size:
                order: 5
                short: z
                type: integer
                required: false
                default: 1000
                description: "largest DNA insert size that can be sequenced by the paired-end method in use"
    read-pair-filtering:
        options:
            primer-match-length:
                order: 1
                short: e
                type: integer
                required: false
                default: 25 # ~20-base primer plus ~5 internal base match space
                description: "perform amplicon primer matching over -e base pairs at the ends of read-pairs"
            max-primer-mismatches:
                order: 2
                short: E
                type: integer
                required: false
                default: 3
                description: "reject read-pairs with more than -E base mismatches over -e primer bases"        
    sv-finding:
        options:
            min-sv-size:
                order: 1
                short: Z
                type: integer
                required: false
                default: 10
                description: "don't report internal deletions or insertions of fewer than -Z base pairs"
package:
    collate: # the pipeline action after which a data package should assembled
        uploadType: svAmplicon # a signal to the Stage 2 framework regarding the package contents
        files:
            manifestFile:
                type: comma-delimited
                manifestType: simple
                file: $COLLATE_PREFIX.manifest.csv
            moleculeTypes:
                type: rds-file
                file: $COLLATE_PREFIX.moleculeTypes.rds
            junctions:
                type: rds-file
                file: $COLLATE_PREFIX.junctions.rds
            amplicons:
                type: tab-delimited
                file: $COLLATE_PREFIX.amplicons.txt
# container:
#     supported: false    # set to true if you maintain a container registry for this pipeline [false]
#     registry:  ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
#     owner:     wilsontelab # REQUIRED: the name of the owner, e.g., user or organization, at 'registry'
#     installer: apt-get  # the installer program used by the container OS, typically apt-get or yum [apt-get]
