---
pipeline:
    name: svAmplicon
    description: "Analyze targeted amplicon sequences for evidence of deletions and other SVs"
    version: v0.0.0
suiteVersions:
    genomex-mdi-tools: main 
actions:
    _global:  
        environment: svAmplicon  
        condaFamilies:
            - genomex-mdi-tools//base
            - genomex-mdi-tools//genome
            - r-4.2
        optionFamilies:
            - genomex-mdi-tools//genome
    align:
        order: 1
        module: genomex-mdi-tools//align/dna-paired-end 
    collate:
        order: 2
        condaFamilies:
            - genomex-mdi-tools//bwa
        optionFamilies: # these options apply to all actions
            - genomex-mdi-tools//bam-format
            - genomex-mdi-tools//read-filtering
            - genomex-mdi-tools//read-merging
            - amplicon-discovery
        resources:
            required:
                total-ram: 32G
            recommended: 
                n-cpu: 16
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 12:00:00
        description: "Group molecules by sequence identity and discover the input amplicon(s)"
    # extract:
    #     order: 2
    #     module: extract
    # find:
    #     order: 3
    #     module: find2
optionFamilies:   
    amplicon-discovery:
        options:
            match-keep-distance:
                order: 1
                short: k
                type: integer
                required: false
                default: 5
                description: "keep molecules with outer endpoints <=k bp from an amplicon index position"  
            match-reject-distance:
                order: 2
                short: K
                type: integer
                required: false
                default: 50
                description: "reject molecules with outer endpoints >k and <=K bp from an amplicon index position" 
            max-amplicons:
                order: 3
                short: A
                type: integer
                required: false
                default: 1
                description: "allow at most -A amplicons to be discovered, in order of abundance"
            min-fraction-add-index:
                order: 4
                short: a
                type: double
                required: false
                default: 0.05
                description: "additional amplicon index positions must exceed this fraction coverage of the first index"


# package:
#     find: # the pipeline action after which a data package should assembled
#         uploadType: svWGS # a signal to the Stage 2 framework regarding the package contents
#         files:
#             metadata:
#                 type: yml
#                 file: $FIND_PREFIX.metadata.yml
#             structuralVariants:
#                 type: rds-file
#                 file: $FIND_PREFIX.structural_variants.rds
#             junctionMolecules:
#                 type: rds-file
#                 file: $FIND_PREFIX.junction_molecules.rds
#             manifestFile:
#                 type: comma-delimited
#                 manifestType: simple
#                 file: $MANIFEST_PREFIX.sample_manifest.csv
#             distributionsZip:
#                 type: zip-file
#                 file: $MANIFEST_PREFIX.distribution_plots.zip
#             coverageFile:
#                 type: rds-file
#                 file: $COVERAGE_PREFIX.rds
# container:
#     supported: false    # set to true if you maintain a container registry for this pipeline [false]
#     registry:  ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
#     owner:     wilsontelab # REQUIRED: the name of the owner, e.g., user or organization, at 'registry'
#     installer: apt-get  # the installer program used by the container OS, typically apt-get or yum [apt-get]



